In [ ]:
import numpy as np


**1 D array**

In [46]:
# creating an array
arr = np.array([1,2,5,4,7,6,3])
arr

array([1, 2, 5, 4, 7, 6, 3])

In [47]:
# gap of 5 from 0th index to last
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[::5])


[1 6]


In [48]:
# slicing an array
print(arr1[1:5])

[2 3 4 5]


In [49]:
print(arr[-3:-1])

[7 6]


In [50]:
print(arr.shape)


(7,)


In [54]:
# searching the aray
a = np.where(arr==4)

a

(array([3]),)

In [58]:
#sorting the array
print(np.sort(arr))

[1 2 3 4 5 6 7]


In [64]:
# reverse sorting the array
print(np.sort(arr)[::-1])

[7 6 5 4 3 2 1]


In [66]:
# Reversing the array
new_array = arr[::-1]
print(new_array)

[3 6 7 4 5 2 1]


In [70]:
#generating random integers between 1 to 100
x = np.random.randint(100)
x

18

**2 D array**

In [ ]:
# printing the shape of an array in (row, column) format
arr3 = np.array([[1,2,3,4],[1,2,3,4],[12,34,5,6]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4]
 [ 1  2  3  4]
 [12 34  5  6]]
(3, 4)


In [ ]:
# data type of an array elements
arr3 = np.array([[1,2,3,4],[1,2,3,4],[12,34,5,6]])
print(arr.dtype)


int64


In [ ]:
# priting all elements from given row
print(arr3[2,:3])

[12 34  5]


In [ ]:
# picking 3rd element from each row
print(arr3[0:3,2])

[3 3 5]


In [36]:
# array reshape
arr3
new_arr = arr3.reshape(4,3)
new_arr

array([[ 1,  2,  3],
       [ 4,  1,  2],
       [ 3,  4, 12],
       [34,  5,  6]])

In [37]:
# iterating array

for x in np.nditer(arr3):
    print(x)

1
2
3
4
1
2
3
4
12
34
5
6


In [39]:
#Enumerated iteration i.e location and its value
for idx, x in np.ndenumerate(arr3):
   print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 1
(1, 1) 2
(1, 2) 3
(1, 3) 4
(2, 0) 12
(2, 1) 34
(2, 2) 5
(2, 3) 6


In [44]:
# joining 2 2d-arrays along rows (axis = 1) or colums (axis = 0)
ar1 = np.array([[1,2,3],[4,5,6]])
ar2 = np.array([[7,8,9],[10,11,12]])
ar0 = np.concatenate((ar1,ar2), axis=0)
print(ar1)
print(" ")
print(ar2)
print(" ")
print(ar0)

[[1 2 3]
 [4 5 6]]
 
[[ 7  8  9]
 [10 11 12]]
 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
