In [7]:
import numpy as np
import pandas as pd

In [8]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [9]:
df = pd.read_csv('/content/House Price India.csv')

In [10]:
df.head()

id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810145  42491                   5                 2.50         3650   
1  6762810635  42491                   4                 2.50         2920   
2  6762810998  42491                   5                 2.75         2910   
3  6762812605  42491                   4                 2.50         3310   
4  6762812919  42491                   3                 2.00         2710   

   lot area  number of floors  waterfront present  number of views  \
0      9050               2.0                   0                4   
1      4000               1.5                   0                0   
2      9480               1.5                   0                0   
3     42998               2.0                   0                0   
4      4500               1.5                   0                0   

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1921                0       122003   
1                       5  ...        1909                0       122004   
2                       3  ...        1939                0       122004   
3                       3  ...        2001                0       122005   
4                       4  ...        1929                0       122006   

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8645   -114.557               2880            5400   
1    52.8878   -114.470               2470            4000   
2    52.8852   -114.468               2940            6600   
3    52.9532   -114.321               3350           42847   
4    52.9047   -114.485               2060            4500   

   Number of schools nearby  Distance from the airport    Price  
0                         2                         58  2380000  
1                         2                         51  1400000  
2                         1                         53  1200000  
3                         3                         76   838000  
4                         1                         51   805000  

[5 rows x 23 columns]

In [11]:
df.shape

(14620, 23)

In [14]:
X = df.iloc[:, 2:7]
X.shape

(14620, 5)

In [17]:
X.head()

number of bedrooms  number of bathrooms  living area  lot area  \
0                   5                 2.50         3650      9050   
1                   4                 2.50         2920      4000   
2                   5                 2.75         2910      9480   
3                   4                 2.50         3310     42998   
4                   3                 2.00         2710      4500   

   number of floors  
0               2.0  
1               1.5  
2               1.5  
3               2.0  
4               1.5

In [16]:
Y = df.iloc[:, -1]
Y.shape

(14620,)

In [18]:
Y.head()

0    2380000
1    1400000
2    1200000
3     838000
4     805000
Name: Price, dtype: int64

In [19]:
#Train-Test splitting
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, random_state= 42)

In [20]:
X_train.shape

(11696, 5)

In [21]:
Y_train.shape

(11696,)

In [22]:
X_test.shape

(2924, 5)

In [23]:
Y_test.shape

(2924,)

In [25]:
# Training and Testing using the LInear regresssion
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
lr = LinearRegression()
lr.fit(X_train,Y_train)

# model evaluation for training set
Y_train_pred = lr.predict(X_train)
mse = mean_squared_error(Y_train, Y_train_pred)
rmse = (np.sqrt(mean_squared_error(Y_train, Y_train_pred)))
r2 = r2_score(Y_train, Y_train_pred)

print("The model performance for training set")
print("--------------------------------------")
print('MSE is {}'.format(mse))
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

# model evaluation for testing set
Y_test_pred = lr.predict(X_test)
mse = mean_squared_error(Y_test, Y_test_pred)
rmse = (np.sqrt(mean_squared_error(Y_test, Y_test_pred)))
r2 = r2_score(Y_test, Y_test_pred)

print("The model performance for testing set")
print("--------------------------------------")
print('MSE is {}'.format(mse))
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))


The model performance for training set
--------------------------------------
MSE is 63917410192.32997
RMSE is 252818.92767815065
R2 score is 0.5215840830754852


The model performance for testing set
--------------------------------------
MSE is 65782876703.604515
RMSE is 256481.72781624136
R2 score is 0.5331864412186775


In [28]:
# Training and Testing using Random Forest Regression
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train,Y_train)

# model evaluation for training set
Y_train_pred = rf.predict(X_train)
mse = mean_squared_error(Y_train, Y_train_pred)
rmse = (np.sqrt(mean_squared_error(Y_train, Y_train_pred)))
r2 = r2_score(Y_train, Y_train_pred)

print("The model performance for training set")
print("--------------------------------------")
print('MSE is {}'.format(mse))
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

# model evaluation for testing set
Y_test_pred = rf.predict(X_test)
mse = mean_squared_error(Y_test, Y_test_pred)
rmse = (np.sqrt(mean_squared_error(Y_test, Y_test_pred)))
r2 = r2_score(Y_test, Y_test_pred)

print("The model performance for testing set")
print("--------------------------------------")
print('MSE is {}'.format(mse))
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))

The model performance for training set
--------------------------------------
MSE is 8278926593.759929
RMSE is 90988.6069448254
R2 score is 0.9380329984336616


The model performance for testing set
--------------------------------------
MSE is 61811240788.50917
RMSE is 248618.66540649993
R2 score is 0.5613702724619194


In [30]:
#Training and Testing using Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(random_state=0)
dtr.fit(X_train,Y_train)

# model evaluation for training set
Y_train_pred = dtr.predict(X_train)
mse = mean_squared_error(Y_train, Y_train_pred)
rmse = (np.sqrt(mean_squared_error(Y_train, Y_train_pred)))
r2 = r2_score(Y_train, Y_train_pred)

print("The model performance for training set")
print("--------------------------------------")
print('MSE is {}'.format(mse))
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

# model evaluation for testing set
Y_test_pred = dtr.predict(X_test)
mse = mean_squared_error(Y_test, Y_test_pred)
rmse = (np.sqrt(mean_squared_error(Y_test, Y_test_pred)))
r2 = r2_score(Y_test, Y_test_pred)

print("The model performance for testing set")
print("--------------------------------------")
print('MSE is {}'.format(mse))
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))

The model performance for training set
--------------------------------------
MSE is 38150880.92020064
RMSE is 6176.639937716998
R2 score is 0.9997144441769152


The model performance for testing set
--------------------------------------
MSE is 104446522814.42442
RMSE is 323181.87265752454
R2 score is 0.25881847282205517
